package dev.pegasus.template.dataProviders

import dev.pegasus.template.R
import dev.pegasus.template.dataClasses.TemplateModel
import dev.pegasus.template.dataClasses.FrameType
import dev.pegasus.template.dataClasses.TemplateType

class DpTemplates {

    // 100 templates by designers will be as follow
    val list = listOf(

        // Christmas templates
        TemplateModel(id = 1, templateType = TemplateType.Portrait, frameType = FrameType.Rectangle, thumbnailImage = R.drawable.img_template_christmas_thumbnail_1, bgImage = R.drawable.img_template_christmas_background_1, template = R.drawable.img_template_christmas_overlay_1, width = 1080F, height = 1350F, frameWidth = 505F, frameHeight = 502F, frameX = 287F, frameY = 278F),
        TemplateModel(id = 2, templateType = TemplateType.Portrait, frameType = FrameType.Rectangle, thumbnailImage = R.drawable.img_template_christmas_thumbnail_2, bgImage = R.drawable.img_template_christmas_background_2, template = R.drawable.img_template_christmas_overlay_2, width = 1080F, height = 1350F, frameWidth = 376F, frameHeight = 388F, frameX = 352F, frameY = 697F),
        TemplateModel(id = 3, templateType = TemplateType.Portrait, frameType = FrameType.Circle, thumbnailImage = R.drawable.img_template_christmas_thumbnail_3, bgImage = R.drawable.img_template_christmas_background_3, template = R.drawable.img_template_christmas_overlay_3, width = 1080F, height = 1350F, frameWidth = 503F, frameHeight = 503F, frameX = 288F, frameY = 423F),
        TemplateModel(id = 4, templateType = TemplateType.Portrait, frameType = FrameType.Rectangle, thumbnailImage = R.drawable.img_template_christmas_thumbnail_4, bgImage = R.drawable.img_template_christmas_background_4, template = R.drawable.img_template_christmas_overlay_4, width = 1080F, height = 1350F, frameWidth = 430F, frameHeight = 425F, frameX = 163F, frameY = 522F),
        TemplateModel(id = 5, templateType = TemplateType.Portrait, frameType = FrameType.Rectangle, thumbnailImage = R.drawable.img_template_christmas_thumbnail_5, bgImage = R.drawable.img_template_christmas_background_5, template = R.drawable.img_template_christmas_overlay_5, width = 1080F, height = 1350F, frameWidth = 790F, frameHeight = 438F, frameX = 129F, frameY = 506F),
        TemplateModel(id = 6, templateType = TemplateType.Portrait, frameType = FrameType.Circle, thumbnailImage = R.drawable.img_template_christmas_thumbnail_6, bgImage = R.drawable.img_template_christmas_background_6, template = R.drawable.img_template_christmas_overlay_6, width = 1080F, height = 1350F, frameWidth = 397F, frameHeight = 397F, frameX = 341F, frameY = 456F),

        // New Year templates
        TemplateModel(id = 7, templateType = TemplateType.Portrait, frameType = FrameType.Rectangle, thumbnailImage = R.drawable.img_template_newyear_thumbnail_1, bgImage = R.drawable.img_template_newyear_background_1, template = R.drawable.img_template_newyear_overlay_1, width = 1080F, height = 1350F, frameWidth = 535F, frameHeight = 401F, frameX = 265F, frameY = 554F),
        TemplateModel(id = 8, templateType = TemplateType.Portrait, frameType = FrameType.Rectangle, thumbnailImage = R.drawable.img_template_newyear_thumbnail_2, bgImage = R.drawable.img_template_newyear_background_2, template = R.drawable.img_template_newyear_overlay_2, width = 1080F, height = 1350F, frameWidth = 625F, frameHeight = 340F, frameX = 208F, frameY = 520F),
        TemplateModel(id = 9, templateType = TemplateType.Portrait, frameType = FrameType.Circle, thumbnailImage = R.drawable.img_template_newyear_thumbnail_3, bgImage = R.drawable.img_template_newyear_background_3, template = R.drawable.img_template_newyear_overlay_3, width = 1080F, height = 1350F, frameWidth = 454F, frameHeight = 454F, frameX = 286F, frameY = 544F),
        TemplateModel(id = 10, templateType = TemplateType.Portrait, frameType = FrameType.Circle, thumbnailImage = R.drawable.img_template_newyear_thumbnail_4, bgImage = R.drawable.img_template_newyear_background_4, template = R.drawable.img_template_newyear_overlay_4, width = 1080F, height = 1350F, frameWidth = 516F, frameHeight = 516F, frameX = 282F, frameY = 510F),
        TemplateModel(id = 11, templateType = TemplateType.Portrait, frameType = FrameType.Rectangle, thumbnailImage = R.drawable.img_template_newyear_thumbnail_5, bgImage = R.drawable.img_template_newyear_background_5, template = R.drawable.img_template_newyear_overlay_5, width = 1080F, height = 1350F, frameWidth = 713F, frameHeight = 393F, frameX = 167F, frameY = 609F),
        TemplateModel(id = 12, templateType = TemplateType.Portrait, frameType = FrameType.Rectangle, thumbnailImage = R.drawable.img_template_newyear_thumbnail_6, bgImage = R.drawable.img_template_newyear_background_6, template = R.drawable.img_template_newyear_overlay_6, width = 1080F, height = 1350F, frameWidth = 607F, frameHeight = 423F, frameX = 108F, frameY = 602F),

        // Birthday templates
        TemplateModel(id = 13, templateType = TemplateType.Portrait, frameType = FrameType.Circle, thumbnailImage = R.drawable.img_template_birthday_thumbnail_1, bgImage = R.drawable.img_template_birthday_background_1, template = R.drawable.img_template_birthday_overlay_1, width = 1080F, height = 1350F, frameWidth = 552F, frameHeight = 552F, frameX = 264F, frameY = 399F),
        TemplateModel(id = 14, templateType = TemplateType.Portrait, frameType = FrameType.Rectangle, thumbnailImage = R.drawable.img_template_birthday_thumbnail_2, bgImage = R.drawable.img_template_birthday_background_2, template = R.drawable.img_template_birthday_overlay_2, width = 1080F, height = 1350F, frameWidth = 440F, frameHeight = 440F, frameX = 319F, frameY = 455F),
        TemplateModel(id = 15, templateType = TemplateType.Portrait, frameType = FrameType.Rectangle, thumbnailImage = R.drawable.img_template_birthday_thumbnail_3, bgImage = R.drawable.img_template_birthday_background_3, template = R.drawable.img_template_birthday_overlay_3, width = 1080F, height = 1350F, frameWidth = 520F, frameHeight = 500F, frameX = 268F, frameY = 418F),
        TemplateModel(id = 16, templateType = TemplateType.Portrait, frameType = FrameType.Circle, thumbnailImage = R.drawable.img_template_birthday_thumbnail_4, bgImage = R.drawable.img_template_birthday_background_4, template = R.drawable.img_template_birthday_overlay_4, width = 1080F, height = 1350F, frameWidth = 507F, frameHeight = 507F, frameX = 272F, frameY = 418F),
        TemplateModel(id = 17, templateType = TemplateType.Portrait, frameType = FrameType.Rectangle, thumbnailImage = R.drawable.img_template_birthday_thumbnail_5, bgImage = R.drawable.img_template_birthday_background_5, template = R.drawable.img_template_birthday_overlay_5, width = 1080F, height = 1350F, frameWidth = 477F, frameHeight = 649F, frameX = 360F, frameY = 483F),
        TemplateModel(id = 18, templateType = TemplateType.Portrait, frameType = FrameType.Circle, thumbnailImage = R.drawable.img_template_birthday_thumbnail_6, bgImage = R.drawable.img_template_birthday_background_6, template = R.drawable.img_template_birthday_overlay_6, width = 1080F, height = 1350F, frameWidth = 410F, frameHeight = 410F, frameX = 335F, frameY = 535F),

        // Anniversary templates
        TemplateModel(id = 19, templateType = TemplateType.Portrait, frameType = FrameType.Rectangle, thumbnailImage = R.drawable.img_template_anniversary_thumbnail_1, bgImage = R.drawable.img_template_anniversary_background_1, template = R.drawable.img_template_anniversary_overlay_1, width = 1080F, height = 1350F, frameWidth = 490F, frameHeight = 753F, frameX = 434F, frameY = 505F),
        TemplateModel(id = 20, templateType = TemplateType.Portrait, frameType = FrameType.Circle, thumbnailImage = R.drawable.img_template_anniversary_thumbnail_2, bgImage = R.drawable.img_template_anniversary_background_2, template = R.drawable.img_template_anniversary_overlay_2, width = 1080F, height = 1350F, frameWidth = 445F, frameHeight = 445F, frameX = 313F, frameY = 227F),
        TemplateModel(id = 21, templateType = TemplateType.Portrait, frameType = FrameType.Rectangle, thumbnailImage = R.drawable.img_template_anniversary_thumbnail_3, bgImage = R.drawable.img_template_anniversary_background_3, template = R.drawable.img_template_anniversary_overlay_3, width = 1080F, height = 1350F, frameWidth = 497F, frameHeight = 477F, frameX = 274F, frameY = 424F),
        TemplateModel(id = 22, templateType = TemplateType.Portrait, frameType = FrameType.Rectangle, thumbnailImage = R.drawable.img_template_anniversary_thumbnail_4, bgImage = R.drawable.img_template_anniversary_background_4, template = R.drawable.img_template_anniversary_overlay_4, width = 1080F, height = 1350F, frameWidth = 481.95F, frameHeight = 646.69F, frameX = 289F, frameY = 399.77F),
        TemplateModel(id = 23, templateType = TemplateType.Portrait, frameType = FrameType.Rectangle, thumbnailImage = R.drawable.img_template_anniversary_thumbnail_5, bgImage = R.drawable.img_template_anniversary_background_5, template = R.drawable.img_template_anniversary_overlay_5, width = 1080F, height = 1350F, frameWidth = 635F, frameHeight = 620F, frameX = 200F, frameY = 434F),
        TemplateModel(id = 24, templateType = TemplateType.Portrait, frameType = FrameType.Rectangle, thumbnailImage = R.drawable.img_template_anniversary_thumbnail_6, bgImage = R.drawable.img_template_anniversary_background_6, template = R.drawable.img_template_anniversary_overlay_6, width = 1080F, height = 1350F, frameWidth = 558.45F, frameHeight = 484F, frameX = 251.79F, frameY = 441F),

    )

}